Controllers/ClotheController.cs
using JNCollection.Website.Models;
using JNCollection.Website.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JNCollection.Website.Controllers
{
    public class ClotheController : Controller
    {
        private readonly IClotheRepository _clothesRepository;
        private readonly ICategoryRepository _categoryRepository;

        public ClotheController(IClotheRepository clothesRepository, ICategoryRepository categoryRepository)
        {
            _clothesRepository = clothesRepository;
            _categoryRepository = categoryRepository;
        }

        public ViewResult List()
        {
            ClotheListViewModel clotheListViewModel = new ClotheListViewModel();
            clotheListViewModel.clothes = _clothesRepository.AllClothes;

            clotheListViewModel.CurrentCategory = "Man wear";
            return View(clotheListViewModel);
        }

        public IActionResult Details(int id)
        {
            var clothe = _clothesRepository.GetClotheById(id);
            if (clothe == null)
                return NotFound();
            return View(clothe);
        }
    }
}

Controllers/HomeController.cs
using JNCollection.Website.Models;
using JNCollection.Website.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JNCollection.Website.Controllers
{
    public class HomeController : Controller
    {
        private readonly IClotheRepository _clotheRepository;

        public HomeController(IClotheRepository clotheRepository)
        {
            _clotheRepository = clotheRepository;
        }
        public IActionResult Index()
        {
            var homeVieModel = new HomeViewModel
            {
                ClotheOfTheWeek = _clotheRepository.ClothesOfTheWeek
            };

            return View(homeVieModel);
        }
    }
}


Controllers/ShoppingCartController.cs
using JNCollection.Website.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JNCollection.Website.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IClotheRepository _clotheRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IClotheRepository clotheRepository, ShoppingCart shoppingCart)
        {
            _clotheRepository = clotheRepository;
            _shoppingCart = shoppingCart;
        }
        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItem();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int clotheId)
        {
            var selectedClothe = _clotheRepository.AllClothes.FirstOrDefault(p => p.ClotheId == clotheId);

            if (selectedClothe != null)
            {
                _shoppingCart.AddToCart(selectedClothe, 1);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Clothe/Details.cshtml
@model Clothe

<h2>@Model.Name</h2>

<div class="thumbnail">
    <img alt="@Model.Name" src="@Model.ImageUrl"/>
    <div class="caption-full">
        <h3 class="pull-right">@Model.Price</h3>
        <h3>
            <a href="#">@Model.Name</a>
        </h3>
        <h4>@Model.ShortDescription</h4>
        <p>@Model.LongDescription</p>
    </div>
</div>

Views/Clothe/List.cshtml
@model ClotheListViewModel

<h1>@Model.CurrentCategory</h1> 
@foreach (var clothe in Model.clothes)
{
    <partial name="_ClotheCard" model="clothe" />
}





Views/Home/Index.cshtml
@model HomeViewModel

@*<partial name="_Carousel" />*@

<h2>Clothes of the week</h2>
<h4>Our weekly selection - just for you</h4>

<div class="row">
    @foreach(var clothe in Model.ClotheOfTheWeek)
            {
                <partial name="_ClotheCard" model="clothe" />
            }
</div>

Views/Shared/_Carousel.cshtml
@*<h1 style="background-color:white">SLIDE SHOW</h1>*@

<div class="test">
    <div class="row carousel-holder">
        <div class="col-md-12" style="background-color: red; padding: 20px">
            <div id="carousel--example-generic" class="carousel-slide">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active" >
                        <img class="slide-image" style="background-color:white; padding:100px" src="~/images/kids1.png" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="~/images/womem1.png" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="~/images/man2.png" alt="">
                    </div>

                </div>
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>

        </div>

    </div>
</div>


Views/Shared/_ClotheCard.cshtml
@model Clothe

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbanailUrl" alt="">
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Clothe" asp-action="Details" asp-route-id="@Model.ClotheId">@Model.Name</a>
            </h3>
            <p>@Model.Category.CategoryName</p>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" >
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#b-exam">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collopse-1">
            <ul class="nav navbar-nav">
                <li><a asp-controller="Clothe" asp-action="List">Clothes</a></li>
            </ul>
            
        </div>
    </div>

</nav>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" src="~/images/JN.png"/>
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>